name: stockito
description: A new Flutter project called Stockito.
publish_to: 'none'
version: 0.9.8+8

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  sqflite: ^2.3.2
  path: ^1.9.0
  get_it: ^7.6.4
  intl: ^0.20.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  bloc_test: ^9.1.5
  mockito: ^5.4.4
  build_runner: ^2.4.7
  fake_async: ^1.3.1
  sqflite_common_ffi: ^2.3.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/app_icon.png
    - lib/l10n/
